### ISSUE TITLE
关于install中，创建任务计划的建议

### ISSUE THREAD

**Issue by 2220545672** [star2000/BingWallpaper#1]
建议触发器，改为事件触发：网络连接成功
网络连接事件在事件管理器中位于：“应用程序和服务日志\Microsoft\Windows\NetworkProfile”
可能的事件ID：4004

**Comment by star2000** [comment]
这将意味着每次网络连接成功都会更新壁纸，相比于现在使用`-RunOnlyIfNetworkAvailable`选项有哪些好处呢？

**Comment by 2220545672** [comment]
之前没注意到这个选项，是我考虑不周，感谢您的解答
