### ISSUE TITLE
手动刷新 无法找到脚本文件“C:\ProgramData\BingWallpaper.vbs”。

### ISSUE THREAD

**Issue by mailsex** [star2000/BingWallpaper#4]
安装完成后，手动刷新无法找到脚本文件“C:\ProgramData\BingWallpaper.vbs”。可能是我的环境变量设置出错了，能不能给一个更详细的说一些环境变量设置教程呢。谢谢
![image](https://user-images.githubusercontent.com/10483712/102730124-74cd3080-436e-11eb-9672-c4cbc9570b4e.png)

**Comment by mailsex** [comment]
我是按照这样设置的
setx "WallpaperPath" "D:\Downloads\新建文件夹"
setx "WallpaperResolution" "UHD"
setx "WallpaperEnSearch" "1"
setx "WallpaperDaysAgo" "0"
![image](https://user-images.githubusercontent.com/10483712/102730323-5156b580-436f-11eb-9114-b9da13025888.png)

**Comment by star2000** [comment]
两种原因, 1.安装成功后这个文件被杀毒软件删掉了. 2.安装过程失败.
解决方法: 再次执行安装命令

**Comment by mailsex** [comment]
还真是被卡巴斯基删掉了。谢谢。
