### ISSUE TITLE
运行安装命令报错

### ISSUE THREAD

**Issue by thy646742** [star2000/BingWallpaper#6]
运行readme.md里的安装命令后提示

> 设置“SecurityProtocol”时发生异常:“由于枚举值无效，无法将值“3312”转换为类型“System.Net.SecurityProtocolType”。请指定以下枚举值之一，然后重试。可能的枚举值为“Ssl3、Tls”。”
所在位置 行:1 字符: 28<br>+ [Net.ServicePointManager]:: <<<< SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor 3072; (New-Object Net.WebClient).DownloadString('https://raw.fastgit.org/star2000/BingWallpaper/master/uninstall.ps1') | iex
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException

运行下载install.ps1仍然如此。

**Comment by star2000** [comment]
按顺序下载安装以下两个包
[Windows .NET Framework 4.8](https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net48-offline-installer)
[x64位 Windows Management Framework 5.1](https://go.microsoft.com/fwlink/?linkid=839523)

参考自：[安装和配置 WMF 5.1](https://docs.microsoft.com/zh-cn/powershell/scripting/windows-powershell/wmf/setup/install-configure)
