### ISSUE TITLE
双显示器或更多个显示器，显示器壁纸黑屏。

### ISSUE THREAD

**Issue by mailsex** [star2000/BingWallpaper#7]
***

**Comment by star2000** [comment]
未能复现你的情况，我用HDMI转VGA的副屏一切正常。
建议的测试方式如下
1. 准备一个空白U盘
2. 制作win10安装盘
    - 用[MediaCreationTool20H2](https://go.microsoft.com/fwlink/?LinkId=691209)预计耗时1小时，
    - 用手机（或浏览器User-Agent改为非Windows）访问[官网](https://www.microsoft.com/zh-cn/software-download/windows10ISO)，复制链接后，用迅雷下载，然后用rufus写入U盘，虽然更麻烦，但预计耗时30分钟
3. 用磁盘管理，把最大的固态硬盘分区压缩出40960MB用于安装第二个Win10
4. 设置》更新和安全》恢复》立即重新启动
5. 将Win10安装到之前分出来的部分
6. 进入第二个Win10测试问题是否还存在
    - 如果问题解决了，更新系统
        - 若还是没问题，则你该准备迁移数据到新系统了
        - 假如问题又出现了，则应该反馈给微软
    - 若问题没有解决，更新系统
        - 若问题解决了，回到旧系统更新系统
            - 若旧系统更新了也没解决，迁移数据吧，叫你养蛊
            - 若旧系统更新后解决了，则可删除新系统的盘，回收空间
        - 若问题仍旧没有解决，换根连接线
            - 若换线解决了，反馈微软
            - 若仍未解决，再说

**Comment by mailsex** [comment]
谢谢你详细的建议。我测试一下。

**Comment by GiaSen** [comment]
Did you fix that? I am getting same issue on Windows 11 22621.963

**Comment by star2000** [comment]
> Did you fix that? I am getting same issue on Windows 11 22621.963

My secondary screen is fine. Maybe you should try again after reinstalling the system. If it still doesn’t work, you can try to fix it.

**Comment by mailsex** [comment]
> Did you fix that? I am getting same issue on Windows 11 22621.963

NO,I need to manually set the wallpaper  every day

**Comment by star2000** [comment]
调试步骤如下
下载wallup.ps1
```ps1
SystemParametersInfo(20, 0, $WallpaperBitmap, 3)
```
修改这里最后的3为其他任意正整数
然后执行wallup.ps1

如果正常了发起一个pull request

另外我不能理解，就好像居然有人宁愿走路也不修自行车，甚至不问一下该怎么修

**Comment by DavidZhang73** [comment]
One **guess** is the following line: https://github.com/star2000/BingWallpaper/blob/0de315f28993efd998befc020e2dec566d26174d/wallup.ps1#L26
deletes the `WallpaperBitmap` from the disk.
No idea why Windows still needs it after setting the wallpaper.
But after removing this line, I no longer have this black screen issue with multiple monitors.

**Comment by star2000** [comment]
> One **guess** is the following line:
> 
> https://github.com/star2000/BingWallpaper/blob/0de315f28993efd998befc020e2dec566d26174d/wallup.ps1#L26
> 
> 
> deletes the `WallpaperBitmap` from the disk.
> No idea why Windows still needs it after setting the wallpaper.
> But after removing this line, I no longer have this black screen issue with multiple monitors.

Okay, I'll change it now
